version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro #read-only so it doesnt change the config

  node-app:
    build: .
    image: iamvieve/node-app
    environment: 
      - PORT=3000
    depends_on: 
      - mongo

  mongodb: #using the built in image from hub no need to customize
    image: mongo #to grab the image from docker hub
    environment: #env var to make sure mongo container work properly by providing root usernamr and root password
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes: #
      - mong-db:/data/db #anonymous named volume

  redis:
    image: redis




volumes:
  mongo-db: